### ISSUE TITLE
Package not available in R 4

### ISSUE THREAD

**Issue by seoanezonjic** [nathanhaigh/pcit#1]
Hi @nathanhaigh 
I've using your package for correlation expression analysis in some projects, but when I moved to R 4 your package is not longer available. Do you think to build a new release for R 4?  It seems that you didn't continue the PCIT development for a long time, if you don't think to adapt the package maybe you know an alternative package to perform a similar analysis. If so, I would like to know your suggestions.
Thank you in advance
Pedro Seoane

**Comment by nathanhaigh** [comment]
Hi Pedro,

I'll have a look back as to why it was dropped for R v4. This might take several weeks so my apologies for the delay.

**Comment by seoanezonjic** [comment]
Hi @nathanhaigh 
Don't worry, I understand that adapt the package to R4 takes time. I'll wait to your R4 release.
Thank you in advance.
Pedro Seoane

**Comment by seoanezonjic** [comment]
Hi @nathanhaigh

I would like to know whether  any development about the package update to R 4. In our lab we are in process of publish our package in bioconductor and the checks reject the PCIT dependence. This forces us to remove the PCIT related code, but this is our last solution to this problem, your package is very useful for us in specific situations.
Thank you in advance.
Pedro Seoane

**Comment by nathanhaigh** [comment]
Hi @seoanezonjic

Unfortunately I don't have any updates at this time. End of year rush means I haven't had any time to spend on this yet.

Do you have a timeline for when you would need to make this decision as to include/remove PCIT as a dependency?

Cheers,
Nathan

**Comment by seoanezonjic** [comment]
Hi @nathanhaigh 

We want to submit the package to bioconductor between this week and the second week of january. To deal with this problem we have created a branch in our repository that contains the PCIT related code. When you have a PCIT release for R4, we'll merge this branch with the main and then, we'll update our Bioconductor package. In this way, you have plenty of time to update your package and we can do the submission without problems.
Thank you for your attention
Pedro Seoane

**Comment by nathanhaigh** [comment]
@seoanezonjic 

I've updated the code and it should now work with R 4.0. However, it won't appear on CRAN until sometime in January due to the CRAN Submission Team being on leave.

In the meantime, you may be able to drop the PCIT code from your repo and have it installed from github using:

```R
# Install tag v1.6.0
devtools::install_github("nathanhaigh/pcit@v1.6.0")
```

I'll leave this issue open until I have a new package available in CRAN.

**Comment by seoanezonjic** [comment]
Hi @nathanhaigh 
This fix is good for us, we can work with our package to send it to Bioconductor and use a full internal version that calls to your current PCIT. When the PCIT release is done for R4, we merge both versions without problem.
Thank you
Pedro Seoane

**Comment by seoanezonjic** [comment]
Hi @nathanhaigh 
I've kept track of CRAN repository but currently, the PCIT package is still removed. Do you have any idea about what is the problem with your R4 release?
Thank you very much
Pedro Seoane

**Comment by seoanezonjic** [comment]
Hi @nathanhaigh 
Still the same issue:
https://CRAN.R-project.org/package=PCIT
Thank you very much
Pedro Seoane
